### ISSUE TITLE
[BUG] Layout combination leads to sidebar bug

### ISSUE THREAD

**Issue by PacifistRiot** [codefoxes/greenlet#51]
**Describe the bug**
On my site, when I set the theme Default Page Layout settings to use the "col 1 (9), col 2 (3)", then set a Page to use a custom layout of (12), a sidebar still shows up but at the bottom of the page.

**To Reproduce**
1. Go to Customizing > Layout > Main Layout
2. In "Default Page Layout" select the top right selection (col 1 (9), col 2 (3)) then publish.
3. Create/edit a WP page, under Document select "Page Layout", click Custom, and change the page layout to the top left selection (12). Save the page.
4. When looking at the page the sidebar is now at the bottom of the page.

**Expected behavior**
Setting a custom page layout should overwrite the default page layout. In this situation there should be no sidebar.

**System used:**
 - Greenlet Version: 2.1.0
 - WordPress Version: 5.5.3
 - PHP Version: 7.4.3

**Comment by karthikax** [comment]
Thanks for reporting the issue @PacifistRiot
We are able to reproduce the issue. We should have a fix soon

**Comment by karthikax** [comment]
This issue has been fixed with version 2.2.0
